receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
                allowed_origins:
                  - "http://*"
                  - "https://*"

exporters:
  debug:
    verbosity: "detailed"
 # Data sources: metrics
  prometheus:
    endpoint: "0.0.0.0:9464"
  otlp/jaeger:
      endpoint: jaeger:4317
      tls:
        insecure: true    
  otlphttp:
      endpoint: http://loki:3100/otlp        
  # Data sources: metrics
  # prometheusremotewrite:
  #   endpoint: http://prometheus:9090/api/prom/push
    # When using the official Prometheus (running via Docker)
    # endpoint: 'http://prometheus:9090/api/v1/write', add:
    # tls:
    #   insecure: true

processors:
  batch:

extensions:
  health_check:
  pprof:
  zpages:


service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp/jaeger, debug] 
    metrics:
      receivers: [otlp]
      exporters: [prometheus, debug] 
    logs:
      receivers: [otlp]
      exporters: [otlphttp, debug] 
